---
title: "P8131_HW2_stl2137"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Problem 1
```{r} 
### Import Data
dose_dat <- tibble(
  dose = c(0, 1, 2, 3, 4),
  death = c(2, 8, 15, 23, 27),
  num_total = c(30, 30, 30, 30, 30)
) 

### Data Preparation
resp <- cbind(dose_dat$death, dose_dat$num_total-dose_dat$death)
```

```{r}
## Logit Model
### Summary Statistics
logit_dose_mod <- glm(resp~dose, family = binomial(link='logit'), data = dose_dat)
summary(logit_dose_mod)
plot(dose_dat$dose,dose_dat$death/dose_dat$num_total)

### CI for Beta
vcov(logit_dose_mod)
beta_logit <- logit_dose_mod$coefficients[2]
se_logit <- sqrt(vcov(logit_dose_mod)[2,2])
CI_logit_high <- beta_logit+c(-qnorm(0.025))*se_logit
CI_logit_low <- beta_logit+c(qnorm(0.025))*se_logit

### Deviance 
dev_logit <- sum(residuals(logit_dose_mod,type='deviance')^2)

### Probability of Death Given Dose = 0.01
p_hat_logit = predict(logit_dose_mod, data.frame(dose= 0.01), se.fit=TRUE, type = 'response')
p_logit = p_hat_logit[[1]]
```

```{r}
## Probit Model
### Summary Statistics
probit_dose_mod <- glm(resp~dose, family=binomial(link='probit'), data = dose_dat)
summary(probit_dose_mod)

### CI for Beta
vcov(probit_dose_mod)
beta_probit <- probit_dose_mod$coefficients[2]
se_probit <- sqrt(vcov(probit_dose_mod)[2,2])
CI_probit_high <- beta_probit + c(-qnorm(0.025))*se_probit
CI_probit_low <- beta_probit + c(qnorm(0.025))*se_probit

### Deviance 
dev_probit <- sum(residuals(probit_dose_mod,type='deviance')^2)

### Probability of Death Given Dose = 0.01
p_hat_probit = predict(probit_dose_mod, data.frame(dose= 0.01), se.fit=TRUE, type = 'response')
p_probit = p_hat_probit[[1]]
```

```{r}
### C-log-log Model
clog_dose_mod <- glm(resp~dose, family=binomial(link='cloglog'), data = dose_dat)
summary(clog_dose_mod)

### CI for Beta
vcov(clog_dose_mod)
beta_clog <- clog_dose_mod$coefficients[2]
se_clog <- sqrt(vcov(clog_dose_mod)[2,2])
CI_clog_high <- beta_clog + c(-qnorm(0.025))*se_clog
CI_clog_low <- beta_clog + c(qnorm(0.025))*se_clog

### Deviance 
dev_clog <- sum(residuals(clog_dose_mod,type='deviance')^2)
dev_clog

### Probability of Death Given Dose = 0.01
p_hat_clog = predict(clog_dose_mod, data.frame(dose= 0.01), se.fit=TRUE, type = 'response')
p_clog = p_hat_clog[[1]]
```

```{r}
logit_table <- cbind(beta_logit, CI_logit_low, CI_logit_high, dev_logit, p_logit)
probit_table <- cbind(beta_probit, CI_probit_low, CI_probit_high, dev_probit, p_probit)
clog_table <- cbind(beta_clog, CI_clog_low, CI_clog_high, dev_clog, p_clog)

total_dose_table <- rbind(logit_table, probit_table, clog_table)
knitr::kable(total_dose_table, col.names = c("Estimate of Beta", "Low CI for Beta", "High CI for Beta", "Deviance", "Probability of Death Given Dose = 0.01"), digits = 4)
```

